export const parentName: string;
export const secondLevelTitle: string;
export const secondLevelTitleSelected: string;
export const secondLevelTitleLink: string;
export const thirdLevelContent: string;
export const thirdMenu: string;
export const thirdSelected: string;
export const thirdLevelImg: string;
export const thirdImgName: string;
