/**
 * 抽奖API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { utils } from '../../utils';


export class ApiResult {
  status?: string = undefined;

  msg?: string = undefined;

  data?: string = undefined;

  static Format(data = {}): ApiResult {
    let obj: ApiResult = new ApiResult();
    obj['status'] = utils.convert(data['status'] || obj['status'], 'string');
    obj['msg'] = utils.convert(data['msg'] || obj['msg'], 'string');
    obj['data'] = utils.convert(data['data'] || obj['data'], 'string');
    return obj;
  }
}
