/**
 * 抽奖API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { utils } from '../../utils';
import * as models from './models';


export class ModelDefault {
  msg?: string = undefined;

  data?: models.PrizeHitResult = undefined;

  /**
     * 1为中奖，其余为未中奖
     */
  status?: string = undefined;

  static Format(data = {}): ModelDefault {
    let obj: ModelDefault = new ModelDefault();
    obj['msg'] = utils.convert(data['msg'] || obj['msg'], 'string');
    obj['data'] = utils.convert(
      data['data'] || obj['data'],
      'models.PrizeHitResult'
    );
    obj['status'] = utils.convert(data['status'] || obj['status'], 'string');
    return obj;
  }
}
