/**
 * 抽奖API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { utils } from '../../utils';


export class PrizeHit {
  id?: number = undefined;

  prizeDetailId?: number = undefined;

  hitIndex?: number = undefined;

  hitUserUuid?: string = undefined;

  static Format(data = {}): PrizeHit {
    let obj: PrizeHit = new PrizeHit();
    obj['id'] = utils.convert(data['id'] || obj['id'], 'number');
    obj['prizeDetailId'] = utils.convert(
      data['prizeDetailId'] || obj['prizeDetailId'],
      'number'
    );
    obj['hitIndex'] = utils.convert(
      data['hitIndex'] || obj['hitIndex'],
      'number'
    );
    obj['hitUserUuid'] = utils.convert(
      data['hitUserUuid'] || obj['hitUserUuid'],
      'string'
    );
    return obj;
  }
}
