/**
 * 抽奖API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { utils } from '../../utils';


export class PrizeArea {
  id?: number = undefined;

  prizeId?: number = undefined;

  areaId?: number = undefined;

  static Format(data = {}): PrizeArea {
    let obj: PrizeArea = new PrizeArea();
    obj['id'] = utils.convert(data['id'] || obj['id'], 'number');
    obj['prizeId'] = utils.convert(data['prizeId'] || obj['prizeId'], 'number');
    obj['areaId'] = utils.convert(data['areaId'] || obj['areaId'], 'number');
    return obj;
  }
}
