/**
 * 抽奖API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { utils } from '../../utils';


export class PrizeDetail {
  id?: number = undefined;

  prizeItem?: string = undefined;

  prizeProduct?: string = undefined;

  price?: number = undefined;

  quantity?: number = undefined;

  img?: string = undefined;

  static Format(data = {}): PrizeDetail {
    let obj: PrizeDetail = new PrizeDetail();
    obj['id'] = utils.convert(data['id'] || obj['id'], 'number');
    obj['prizeItem'] = utils.convert(
      data['prizeItem'] || obj['prizeItem'],
      'string'
    );
    obj['prizeProduct'] = utils.convert(
      data['prizeProduct'] || obj['prizeProduct'],
      'string'
    );
    obj['price'] = utils.convert(data['price'] || obj['price'], 'number');
    obj['quantity'] = utils.convert(
      data['quantity'] || obj['quantity'],
      'number'
    );
    obj['img'] = utils.convert(data['img'] || obj['img'], 'string');
    return obj;
  }
}
