/**
 * 抽奖API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export class PrizeDetailDtoList {
  static Format(data = {}): PrizeDetailDtoList {
    let obj: PrizeDetailDtoList = new PrizeDetailDtoList();
    return obj;
  }
}
