/**
 * 抽奖API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { utils } from '../../utils';
import * as models from './models';


export class PrizeDto {
  id?: number = undefined;

  name?: string = undefined;

  /**
     * 开始日期
     */
  startDate?: Date = undefined;

  /**
     * 结束日期
     */
  endDate?: Date = undefined;

  /**
     * 最多中奖次数
     */
  personalHitNumber?: number = undefined;

  /**
     * 预估总抽奖人数
     */
  personalNumber?: number = undefined;

  /**
     * 中奖率
     */
  pct?: string = undefined;

  /**
     * 类型
     */
  type?: number = undefined;

  /**
     * 状态
     */
  status?: number = undefined;

  /**
     * 奖项
     */
  prizeDetails?: models.PrizeDetailDtoList = undefined;

  /**
     * 活动说明
     */
  summary?: string = undefined;

  static Format(data = {}): PrizeDto {
    let obj: PrizeDto = new PrizeDto();
    obj['id'] = utils.convert(data['id'] || obj['id'], 'number');
    obj['name'] = utils.convert(data['name'] || obj['name'], 'string');
    obj['startDate'] = utils.convert(
      data['startDate'] || obj['startDate'],
      'Date'
    );
    obj['endDate'] = utils.convert(data['endDate'] || obj['endDate'], 'Date');
    obj['personalHitNumber'] = utils.convert(
      data['personalHitNumber'] || obj['personalHitNumber'],
      'number'
    );
    obj['personalNumber'] = utils.convert(
      data['personalNumber'] || obj['personalNumber'],
      'number'
    );
    obj['pct'] = utils.convert(data['pct'] || obj['pct'], 'string');
    obj['type'] = utils.convert(data['type'] || obj['type'], 'number');
    obj['status'] = utils.convert(data['status'] || obj['status'], 'number');
    obj['prizeDetails'] = utils.convert(
      data['prizeDetails'] || obj['prizeDetails'],
      'models.PrizeDetailDtoList'
    );
    obj['summary'] = utils.convert(data['summary'] || obj['summary'], 'string');
    return obj;
  }
}
