/**
 * 抽奖API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { utils } from '../../utils';

export class Prize {
  id?: number = undefined;

  name?: string = undefined;

  startDate?: Date = undefined;

  endDate?: Date = undefined;

  personalHitNumber?: number = undefined;

  personalNumber?: number = undefined;

  pct?: number = undefined;

  allowHitAll?: number = undefined;

  type?: boolean = undefined;

  static Format(data = {}): Prize {
    let obj: Prize = new Prize();
    obj['id'] = utils.convert(data['id'] || obj['id'], 'number');
    obj['name'] = utils.convert(data['name'] || obj['name'], 'string');
    obj['startDate'] = utils.convert(
      data['startDate'] || obj['startDate'],
      'Date'
    );
    obj['endDate'] = utils.convert(data['endDate'] || obj['endDate'], 'Date');
    obj['personalHitNumber'] = utils.convert(
      data['personalHitNumber'] || obj['personalHitNumber'],
      'number'
    );
    obj['personalNumber'] = utils.convert(
      data['personalNumber'] || obj['personalNumber'],
      'number'
    );
    obj['pct'] = utils.convert(data['pct'] || obj['pct'], 'number');
    obj['allowHitAll'] = utils.convert(
      data['allowHitAll'] || obj['allowHitAll'],
      'number'
    );
    obj['type'] = utils.convert(data['type'] || obj['type'], 'boolean');
    return obj;
  }
}
